/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Darko.Form;

import com.formdev.flatlaf.fonts.inter.FlatInterFont;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.Socket;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jjose
 */
public class Form_5 extends javax.swing.JPanel {
     private Socket socket;
    /**
     * Creates new form Form_5
     * @param eventRegister
     */
     
     private boolean servidorActivo = false; // Inicialmente, el servidor está inactivo

    public Form_5(ActionListener eventRegister) {
        initComponents();
        FlatInterFont.install();
        jLabel3.setFont(new Font(FlatInterFont.FAMILY, Font.BOLD, 16 ));
        jLabel6.setFont(new Font(FlatInterFont.FAMILY, Font.PLAIN, 11 ));
        jLabel7.setFont(new Font(FlatInterFont.FAMILY, Font.PLAIN, 11 ));
        jLabel10.setFont(new Font(FlatInterFont.FAMILY, Font.BOLD, 13 ));
        jLabel11.setFont(new Font(FlatInterFont.FAMILY, Font.PLAIN, 11 ));
        txtAreaIA.setFont(new Font(FlatInterFont.FAMILY, Font.PLAIN, 20 ));
        
        btnAsistente.setBackground(new Color(59, 59, 59));
        btnAsistente.setForeground(new Color(250, 250, 250));
        btnAsistenteC.setBackground(new Color(59, 59, 59));
        btnAsistenteC.setForeground(new Color(250, 250, 250));
        
        
        
        btnAsistente.addActionListener(eventRegister);
        btnAsistente.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    startClient();
                } catch (IOException ex) {
                    Logger.getLogger(Form_5.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        btnAsistenteC.addActionListener(eventRegister);
        btnAsistenteC.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                closeConnection();
            }
        });
        
        btnEnviar.addActionListener(eventRegister);
        btnEnviar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                sendMessage();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAsistente = new Darko.Swing.Button();
        btnAsistenteC = new Darko.Swing.Button();
        textAreaScroll2 = new textarea.TextAreaScroll();
        txtAreaUser = new textarea.TextArea();
        btnEnviar = new Darko.Swing.Button();
        jLabel11 = new javax.swing.JLabel();
        textAreaScroll3 = new textarea.TextAreaScroll();
        txtAreaIA = new textarea.TextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Darko/Img/megha-ajith-WRST5Pops3E-unsplash.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Darko/Img/hexagons.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Darko/Img/hexagons.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Darko/Img/hexagons.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Darko/Img/hexagons.png"))); // NOI18N

        jLabel3.setText("¡Bienvenido al Asistente Nutricional! ");

        jLabel6.setText("Estoy aquí para ayudarte");

        jLabel7.setText("con consultas, crear dietas personalizadas");

        jLabel10.setText("¿En qué puedo ayudarte hoy?");

        btnAsistente.setText("Abrir asistente");
        btnAsistente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenteActionPerformed(evt);
            }
        });

        btnAsistenteC.setText("Cerrar Asistente");
        btnAsistenteC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAsistenteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenteCActionPerformed(evt);
            }
        });

        textAreaScroll2.setLabelText("Usuario");
        textAreaScroll2.setLineColor(new java.awt.Color(0, 155, 216));

        txtAreaUser.setColumns(20);
        txtAreaUser.setRows(5);
        txtAreaUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtAreaUser.setSelectionColor(new java.awt.Color(204, 204, 204));
        textAreaScroll2.setViewportView(txtAreaUser);

        btnEnviar.setText("Enviar");
        btnEnviar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel11.setText("y brindarte información nutricional.");

        textAreaScroll3.setLabelText("");
        textAreaScroll3.setLineColor(new java.awt.Color(0, 0, 0));

        txtAreaIA.setColumns(20);
        txtAreaIA.setRows(5);
        txtAreaIA.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        txtAreaIA.setSelectionColor(new java.awt.Color(204, 204, 204));
        textAreaScroll3.setViewportView(txtAreaIA);

        jLabel1.setText("Servidor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(textAreaScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAsistenteC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(119, 119, 119))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(195, 195, 195))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(352, 352, 352)
                    .addComponent(textAreaScroll3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1508, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textAreaScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel7)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addGap(36, 36, 36))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAsistenteC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))))
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(textAreaScroll3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(311, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenteActionPerformed
//        try {
//            String pythonExecutable = "python";
//            String pythonScript = "C:\\Users\\jjose\\AsistantNutrition\\assist.py"; 
//
//            ProcessBuilder processBuilder = new ProcessBuilder(pythonExecutable, pythonScript);
//
//            // Redirige la entrada y la salida estándar para evitar bloqueos
//            processBuilder.redirectErrorStream(true); // Combina la salida estándar y de error
//            Process process = processBuilder.start();
//
//            // Lee la salida del proceso en tiempo real
//            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
//            String line;
//            while ((line = reader.readLine()) != null) {
//                System.out.println(line); // Muestra la salida del script en Java
//            }
//
//            int exitCode = process.waitFor();
//
//            if (exitCode == 0) {
//                System.out.println("El script de Python se ejecutó con éxito.");
//            } else {
//                System.err.println("Error al ejecutar el script de Python. Código de salida: " + exitCode);
//                }
//            } catch (IOException | InterruptedException e) {
//                e.printStackTrace();
//        }

    }//GEN-LAST:event_btnAsistenteActionPerformed

    private void btnAsistenteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenteCActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsistenteCActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

    }//GEN-LAST:event_btnEnviarActionPerformed
    
     private void startClient() throws IOException {
        socket = new Socket("localhost", 8080);

        
            servidorActivo = true;

            // Actualiza el texto del jLabel1
            actualizarEstadoServidor();  
//        OutputStream outputStream = socket.getOutputStream();
//        Scanner scanner = new Scanner(System.in);
//
//       while (true) {
//             String message = scanner.nextLine();
//            outputStream.write(message.getBytes());
//
//            InputStream inputStream = socket.getInputStream();
//            byte[] bytes = new byte[1024];
//            int bytesRead = inputStream.read(bytes);
//            String response = new String(bytes, 0, bytesRead);
//
//            System.out.println("Response: " + response);
//        }
    }
     
     private void closeConnection() {
        try {
            socket.close();
            servidorActivo = false; // El servidor está inactivo después de cerrar la conexión
            actualizarEstadoServidor();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // Método para actualizar el texto del jLabel1 según el estado del servidor
    private void actualizarEstadoServidor() {
        if (servidorActivo) {
            jLabel1.setText("Servidor: activo");
        } else {
            jLabel1.setText("Servidor: inactivo");
        }
    }
     
     private void sendMessage() {
        try {
            String message = txtAreaUser.getText();
            OutputStream outputStream = socket.getOutputStream();
            outputStream.write(message.getBytes());

            InputStream inputStream = socket.getInputStream();
            byte[] bytes = new byte[1024];
            int bytesRead = inputStream.read(bytes);
            String response = new String(bytes, 0, bytesRead);

            txtAreaIA.append("Usuario: " + message + "\n");
            txtAreaIA.append("Chatbot: " + response + "\n");

            // Limpia el área de entrada después de enviar el mensaje
            txtAreaUser.setText("");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Darko.Swing.Button btnAsistente;
    private Darko.Swing.Button btnAsistenteC;
    private Darko.Swing.Button btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private textarea.TextAreaScroll textAreaScroll2;
    private textarea.TextAreaScroll textAreaScroll3;
    private textarea.TextArea txtAreaIA;
    private textarea.TextArea txtAreaUser;
    // End of variables declaration//GEN-END:variables
}
